#!/usr/bin/env bash

sudo apt-get update

sudo apt-get -y install build-essential
sudo apt-get -y install openssl
sudo apt-get -y install libreadline6
sudo apt-get -y install libreadline6-dev
sudo apt-get -y install apt-transport-https 
sudo apt-get -y install ca-certificates
sudo apt-get -y install curl
sudo apt-get -y install gnupg-agent
sudo apt-get -y install software-properties-common
sudo apt-get -y install zlib1g
sudo apt-get -y install zlib1g-dev
sudo apt-get -y install libssl-dev
sudo apt-get -y install libyaml-dev
sudo apt-get -y install libsqlite3-dev
sudo apt-get -y install sqlite3
sudo apt-get -y install libxml2-dev
sudo apt-get -y install libxslt-dev
sudo apt-get -y install libgmp-dev
sudo apt-get -y install autoconf
sudo apt-get -y install libc6-dev
sudo apt-get -y install ncurses-dev
sudo apt-get -y install automake
sudo apt-get -y install libtool
sudo apt-get -y install bison
sudo apt-get -y install subversion
sudo apt-get -y install python-software-properties
sudo apt-get -y install ack-grep
sudo apt-get -y install libpq-dev
sudo apt-get -y install libhiredis-dev
sudo apt-get -y install libmemcached-dev
sudp apt-get -y install imagemagick
sudo apt-get -y install libmagickwand-dev
sudo apt-get -y install install libssh-dev
sudo apt-get -y install libqt4-dev
sudo apt-get -y install libqtwebkit-dev
sudo apt-get -y install default-jdk
sudo apt-get -y install zsh
sudo apt-get -y install vim
sudo apt-get -y install tmux

sudo apt-get -y install git
sudo apt-get -y install git-svn
sudo apt-get -y install gitk
sudo apt-get -y install ssh

git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.7.3
echo -e '\n. $HOME/.asdf/asdf.sh' >> ~/.bashrc
echo -e '\n. $HOME/.asdf/completions/asdf.bash' >> ~/.bashrc

curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" 
sudo apt-get update
sudo apt-get -y install docker-ce docker-ce-cli containerd.io
sudo usermod -aG docker $USER
