#!/usr/bin/env bash

sudo apt-get update

sudo apt-get -y install build-essential
sudo apt-get -y install libssl-dev
sudo apt-get -y install libreadline-dev
sudo apt-get -y install libffi-dev
sudo apt-get -y install default-jdk
sudo apt-get -y install software-properties-common
sudo apt-get -y install python-software-properties
sudp apt-get -y install imagemagick
sudo apt-get -y install libmagickwand-dev
sudo apt-get -y install curl
sudo apt-get -y install git
sudo apt-get -y install ssh
sudo apt-get -y install zsh
sudo apt-get -y install tmux
sudo apt-get -y install vim
sudo apt-get -y install ack-grep
sudo apt-get -y install sqlite3
sudo apt-get -y install libsqlite3-dev
sudo apt-get -y install postgresql postgresql-contrib libpq-dev
sudo apt-get -y install redis-server libhiredis-dev
sudo apt-get -y install memcached libmemcached-dev

git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.7.3
echo -e '\n. $HOME/.asdf/asdf.sh' >> ~/.bashrc
echo -e '\n. $HOME/.asdf/completions/asdf.bash' >> ~/.bashrc

curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" 
sudo apt-get update
sudo apt-get -y install docker-ce docker-ce-cli containerd.io
sudo usermod -aG docker $USER
